# Generated by Django 6.0.1 on 2026-01-28 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Производитель')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео-обзор')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Обычная цена')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена со скидкой')),
                ('price_in_euro', models.BooleanField(default=False, verbose_name='Цена в евро')),
                ('free_delivery', models.BooleanField(default=False, verbose_name='Бесплатная доставка')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии на складе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен в каталоге')),
                ('sku', models.CharField(blank=True, help_text='Можно хранить через запятую', max_length=255, verbose_name='Артикул(ы)')),
                ('series', models.CharField(blank=True, max_length=255, verbose_name='Серия товара')),
                ('dimensions', models.CharField(blank=True, help_text='Формат: ДxШxВ в мм', max_length=255, verbose_name='Размеры товара')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Вес товара (кг)')),
                ('heated_volume', models.IntegerField(blank=True, null=True, verbose_name='Объём отапливаемого помещения')),
                ('steam_volume_from', models.IntegerField(blank=True, null=True, verbose_name='Объём парильного помещения, от')),
                ('steam_volume_to', models.IntegerField(blank=True, null=True, verbose_name='Объём парильного помещения, до')),
                ('chimney_diameter', models.IntegerField(blank=True, null=True, verbose_name='Диаметр дымохода (мм)')),
                ('power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Мощность (кВт)')),
                ('stone_weight', models.IntegerField(blank=True, null=True, verbose_name='Масса закладываемых камней')),
                ('material', models.CharField(blank=True, choices=[('stainless_steel', 'Нержавеющая сталь'), ('enameled_steel', 'Эмалированная сталь'), ('ceramic_pipe', 'Керамическая труба'), ('galvanized_steel', 'Оцинкованная сталь'), ('structural_steel', 'Конструкционная сталь'), ('boiler_steel', 'Котловая сталь'), ('cast_iron', 'Чугун'), ('ceramics', 'Керамика'), ('natural_stone', 'Натуральный камень'), ('iron', 'Железо'), ('fireclay', 'Шамот'), ('talc_magnesium', 'Талькомагнезит'), ('metal', 'Металл')], max_length=32, null=True, verbose_name='Вид топки')),
                ('firebox_material', models.CharField(blank=True, choices=[('steel', 'Стальной'), ('fireclay', 'Шамотный'), ('cast_iron', 'Чугунный'), ('cellular_cast_iron', 'Цельнолитый чугунный')], max_length=32, null=True, verbose_name='Материал топки')),
                ('stone_material', models.CharField(blank=True, choices=[('natural', 'Натуральный'), ('artificial', 'Искусственный')], max_length=32, null=True, verbose_name='Материал камня')),
                ('door_type', models.CharField(blank=True, choices=[('with_glass', 'Со стеклом'), ('without_glass', 'Без стекла')], max_length=32, null=True, verbose_name='Дверца')),
                ('door_mechanism', models.CharField(blank=True, choices=[('side_opening', 'Боковое открывание'), ('lift_up', 'Подъемный механизм')], max_length=32, null=True, verbose_name='Механизм открывания дверцы')),
                ('fire_view', models.CharField(blank=True, choices=[('straight_glass', 'Прямое стекло'), ('panoramic_glass', 'Панорамное стекло'), ('g_shaped_glass', 'Г-образное стекло'), ('p_shaped_glass', 'П-образное стекло'), ('prismatic_glass', 'Призматическое стекло'), ('lift_up_mechanism', 'Подъемный механизм'), ('double_sided', 'Двухстороннее')], max_length=32, null=True, verbose_name='Обзор огня')),
                ('glass_count', models.CharField(blank=True, choices=[('one', 'Одно'), ('two', 'Два'), ('three', 'Три'), ('four', 'Четыре')], max_length=32, null=True, verbose_name='Количество стекол')),
                ('fuel_type', models.CharField(blank=True, choices=[('gas', 'Газ'), ('wood', 'Дровяной'), ('electric', 'Электрический'), ('coal', 'Угольный'), ('solid_fuel', 'Твердотопливный'), ('semi_automatic', 'Полуавтоматический'), ('bioethanol', 'Биоэтанол'), ('pellet', 'Пеллетный')], max_length=32, null=True, verbose_name='Тип топлива')),
                ('tank_type', models.CharField(blank=True, choices=[('samovar', 'Самоварный'), ('mounted', 'Навесной'), ('register', 'Регистр')], max_length=32, null=True, verbose_name='Тип бака')),
                ('firebox_type', models.CharField(blank=True, choices=[('with_extension', 'С выносом'), ('without_extension', 'Без выноса')], max_length=32, null=True, verbose_name='Вид топки')),
                ('stone_type', models.CharField(blank=True, choices=[('closed', 'Закрытая'), ('open', 'Открытая'), ('combined', 'Комбинированная'), ('stone_mesh', 'Сетка для камней')], max_length=32, null=True, verbose_name='Каменка')),
                ('water_heating', models.CharField(blank=True, choices=[('with_heat_exchanger', 'С теплообменником'), ('without_heat_exchanger', 'Без теплообменника')], max_length=32, null=True, verbose_name='Нагрев воды')),
                ('placement', models.CharField(blank=True, choices=[('horizontal', 'Горизонтальная'), ('vertical', 'Вертикальная'), ('corner', 'Угловая'), ('central', 'Центральная')], max_length=32, null=True, verbose_name='Расположение топки')),
                ('facing_type', models.CharField(blank=True, choices=[('built_in', 'Встроенный'), ('double_sided', 'Двусторонний'), ('fireplace_frame', 'Каминная рамка'), ('wall_mounted', 'Пристенный'), ('corner', 'Угловой'), ('central', 'Центральный')], max_length=32, null=True, verbose_name='Тип облицовки')),
                ('heat_exchanger', models.BooleanField(default=False, verbose_name='Теплообменник')),
                ('long_burning', models.BooleanField(default=False, verbose_name='Система длительного горения')),
                ('glass_lift', models.BooleanField(default=False, verbose_name='Подъём стекла')),
                ('damper', models.BooleanField(default=False, verbose_name='Шибер')),
                ('cooking_panel', models.BooleanField(default=False, verbose_name='Варочная панель')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='Название страницы товара')),
                ('seo_description', models.TextField(blank=True, verbose_name='Описание страницы товара')),
                ('seo_keywords', models.TextField(blank=True, verbose_name='Ключевые слова товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='products/documents/', verbose_name='Файл')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main_app.product')),
            ],
            options={
                'verbose_name': 'Документ товара',
                'verbose_name_plural': 'Документы товара',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.product')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товара',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Используется в URL', max_length=255, verbose_name='Slug')),
                ('menu_name', models.CharField(blank=True, max_length=255, verbose_name='Название для меню')),
                ('browser_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок вкладки браузера')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Описание страницы для поиска')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключевые слова для поиска')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Сортировка внутри одного родителя', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Раздел активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main_app.section', verbose_name='Родительский раздел')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['parent__id', 'ordering', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sections',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.section', verbose_name='Разделы'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['slug'], name='main_app_se_slug_c22ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['parent'], name='main_app_se_parent__bab13a_idx'),
        ),
    ]
