# Generated by Django 6.0.1 on 2026-01-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sections',
            field=models.ManyToManyField(blank=True, to='main_app.section', verbose_name='Разделы'),
        ),
    ]
