# Generated by Django 6.0.1 on 2026-02-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_product_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='productdocument',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveIndex(
            model_name='section',
            name='main_app_se_slug_c22ad2_idx',
        ),
        migrations.RemoveIndex(
            model_name='section',
            name='main_app_se_parent__bab13a_idx',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='ProductDocument',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
