# Generated by Django 6.0.1 on 2026-02-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_portfolio_portfolioimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Локация')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('installation_time', models.CharField(blank=True, max_length=255, verbose_name='Время затраченное на монтаж')),
                ('work_description', models.TextField(verbose_name='Произведённые работы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование проекта')),
                ('client_problem', models.CharField(max_length=255, verbose_name='Боль клиента')),
                ('catalog_type', models.CharField(choices=[('bath_stoves', 'Портфолио банных печей'), ('fireplace_stoves', 'Портфолио печей-каминов'), ('chimneys', 'Портфолио дымохода'), ('fireplaces', 'Портфолио каминов')], max_length=50, verbose_name='Раздел каталога')),
                ('project_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость проекта')),
                ('production_time', models.CharField(blank=True, max_length=255, verbose_name='Срок производства работ')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Дата производства работ')),
                ('object_type', models.CharField(blank=True, max_length=255, verbose_name='Тип объекта')),
                ('work_types', models.CharField(blank=True, max_length=255, verbose_name='Виды работ')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, to='main_app.product', verbose_name='Товары участвующие в проекте')),
            ],
            options={
                'verbose_name': 'Портфолио каталога',
                'verbose_name_plural': 'Портфолио каталога',
            },
        ),
        migrations.CreateModel(
            name='CatalogPortfolioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='История проекта')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_blocks', to='main_app.catalogportfolio')),
            ],
            options={
                'verbose_name': 'История проекта',
                'verbose_name_plural': 'История проекта',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='CatalogPortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog_portfolio/', verbose_name='Изображение')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='main_app.catalogportfolio')),
            ],
            options={
                'verbose_name': 'Изображение проекта',
                'verbose_name_plural': 'Изображения проекта',
            },
        ),
        migrations.CreateModel(
            name='CatalogPortfolioProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog_portfolio_product/', verbose_name='Изображение')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_product_image', to='main_app.catalogportfolio', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Товар участвовавший в проекте',
                'verbose_name_plural': 'Товары участвовавшие в проекте',
            },
        ),
    ]
