# Generated by Django 6.0.1 on 2026-02-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_review_catalogportfolio_catalogportfoliohistory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatalogPortfolioProduct',
            new_name='CatalogPortfolioProductImage',
        ),
        migrations.RemoveField(
            model_name='catalogportfolio',
            name='products',
        ),
    ]
