# Generated by Django 6.0.1 on 2026-02-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_product_is_bestseller_product_is_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='1', max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
