# Generated by Django 5.2.11 on 2026-02-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на видео-обзор'),
        ),
    ]
