# Generated by Django 5.2.11 on 2026-02-22 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_product_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='1', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_app.product', verbose_name='Продукт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='review',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=12, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='video_url',
            field=models.TextField(verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='review',
            name='work_description',
            field=models.TextField(verbose_name='Что сделано'),
        ),
    ]
