# Generated by Django 5.2.11 on 2026-02-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_review_name_review_product_alter_review_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(default='1', upload_to='manufacturers/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
