# Generated by Django 5.2.11 on 2026-02-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_manufacturer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Чем больше значение — тем выше бренд', verbose_name='Приоритет'),
        ),
    ]
