# Generated by Django 5.2.11 on 2026-02-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_manufacturer_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='image',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(default='1', upload_to='manufacturers/', verbose_name='Логотип'),
            preserve_default=False,
        ),
    ]
