# Generated by Django 5.2.11 on 2026-02-22 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_manufacturer_image_manufacturer_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата работ'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Указывайте количество в днях', verbose_name='Срок работ'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='main',
            field=models.BooleanField(default=False, help_text='Отметьте, если это портфолио должно быть на главной странице', verbose_name='На главную'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='object_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип объекта'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='picture',
            field=models.ImageField(default='1', upload_to='portfolio_image/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='product',
            field=models.ForeignKey(default='1', help_text='Выберите товар к которому относится данное портфолио', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='main_app.product', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='type_work',
            field=models.TextField(blank=True, null=True, verbose_name='Тип работ'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='video_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
    ]
