# Generated by Django 5.2.11 on 2026-02-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_portfolio_options_remove_portfolio_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogportfolioproductimage',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='catalogportfolioimage',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='CatalogPortfolioHistory',
        ),
        migrations.DeleteModel(
            name='CatalogPortfolioProductImage',
        ),
        migrations.DeleteModel(
            name='CatalogPortfolio',
        ),
        migrations.DeleteModel(
            name='CatalogPortfolioImage',
        ),
    ]
