# Generated by Django 5.2.11 on 2026-02-23 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_catalogportfolioproductimage_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='slug',
            field=models.CharField(default='1', max_length=255, unique=True, verbose_name='ЧПУ (slug)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='video',
            field=models.TextField(blank=True, verbose_name='Видео'),
        ),
        migrations.CreateModel(
            name='ManufacturerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='manufacturer_images/', verbose_name='Фото')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Фото производителя',
                'verbose_name_plural': 'Фото производителей',
                'ordering': ['ordering'],
            },
        ),
    ]
