# Generated by Django 5.2.11 on 2026-02-23 12:24

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_catalogportfolioproductimage_portfolio_and_more'),
    ]

    def _fill_manufacturer_slugs(apps, schema_editor):
        Manufacturer = apps.get_model("main_app", "Manufacturer")

        used = set(
            s for s in Manufacturer.objects.exclude(slug__isnull=True)
            .exclude(slug="")
            .values_list("slug", flat=True)
        )

        for m in Manufacturer.objects.all().order_by("id"):
            current = (m.slug or "").strip()
            if current:
                base = current
            else:
                base = slugify(m.name) or f"manufacturer-{m.id}"

            slug = base
            i = 1
            while slug in used:
                i += 1
                slug = f"{base}-{i}"

            m.slug = slug
            m.save(update_fields=["slug"])
            used.add(slug)

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ (slug)'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='video',
            field=models.TextField(blank=True, verbose_name='Видео'),
        ),
        migrations.RunPython(_fill_manufacturer_slugs, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=models.CharField(max_length=255, unique=True, verbose_name='ЧПУ (slug)'),
        ),
        migrations.CreateModel(
            name='ManufacturerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='manufacturer_images/', verbose_name='Фото')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Фото производителя',
                'verbose_name_plural': 'Фото производителей',
                'ordering': ['ordering'],
            },
        ),
    ]
