# Generated by Django 5.2.11 on 2026-02-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_manufacturer_description_manufacturer_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='picture',
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_image/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.portfolio', verbose_name='Портфолио')),
            ],
            options={
                'verbose_name': 'Фото портфолио',
                'verbose_name_plural': 'Фото портфолио',
                'ordering': ['order', 'id'],
            },
        ),
    ]
