# Generated by Django 5.2.11 on 2026-02-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_portfolio_picture_portfolioimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Картинка, отображаемая как превью видео', null=True, upload_to='reviews/video_preview/', verbose_name='Превью видео'),
        ),
    ]
