# Generated by Django 5.2.11 on 2026-02-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_review_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='facing_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long_burning',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='placement',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stone_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='water_heating',
        ),
        migrations.AddField(
            model_name='product',
            name='cladding_material',
            field=models.CharField(blank=True, choices=[('stone', 'Камень'), ('ceramics', 'Керамика'), ('metal', 'Металл')], max_length=32, null=True, verbose_name='Материал облицовки'),
        ),
        migrations.AddField(
            model_name='product',
            name='combustion_type',
            field=models.CharField(blank=True, choices=[('long_burning', 'Длительного горения'), ('classic', 'Классическая')], max_length=32, null=True, verbose_name='Тип горения'),
        ),
        migrations.AddField(
            model_name='product',
            name='firebox_orientation',
            field=models.CharField(blank=True, choices=[('horizontal', 'Горизонтальная'), ('vertical', 'Вертикальная')], max_length=32, null=True, verbose_name='Ориентация топки'),
        ),
        migrations.AddField(
            model_name='product',
            name='heater_type',
            field=models.CharField(blank=True, choices=[('closed', 'Закрытая'), ('open', 'Открытая'), ('combined', 'Комбинированная'), ('mesh_for_stones', 'Сетка для камней')], max_length=32, null=True, verbose_name='Каменка'),
        ),
        migrations.AddField(
            model_name='product',
            name='installation_type',
            field=models.CharField(blank=True, choices=[('wall', 'Пристенная'), ('corner', 'Угловая'), ('central', 'Центральная'), ('built_in', 'Встроенная'), ('two_sided', 'Двухсторонняя')], max_length=32, null=True, verbose_name='Тип установки'),
        ),
        migrations.AddField(
            model_name='product',
            name='purpose',
            field=models.CharField(blank=True, choices=[('home', 'Для дома'), ('cottage', 'Для дачи'), ('sauna_bath', 'Для сауны / бани')], max_length=32, null=True, verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='product',
            name='steam_room_volume',
            field=models.CharField(blank=True, choices=[('lt_20', 'до 20 м³'), ('20_30', '20–30 м³'), ('30_50', '30–50 м³'), ('gt_50', 'более 50 м³')], max_length=32, null=True, verbose_name='Площадь/объём парной'),
        ),
        migrations.AddField(
            model_name='product',
            name='water_circuit',
            field=models.BooleanField(default=False, verbose_name='Водяной контур'),
        ),
        migrations.AlterField(
            model_name='product',
            name='chimney_diameter',
            field=models.CharField(blank=True, choices=[('115', '115'), ('120', '120'), ('150', '150'), ('180', '180')], max_length=32, null=True, verbose_name='Диаметр дымохода'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Формат: ДxШxВ в мм', max_length=255, verbose_name='Габариты (Д×Ш×В, мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='door_mechanism',
            field=models.CharField(blank=True, choices=[('side_opening', 'Боковое открывание'), ('lift_up', 'Подъемный механизм')], max_length=32, null=True, verbose_name='Механизм открывания двери'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fire_view',
            field=models.CharField(blank=True, choices=[('straight_glass', 'С прямым стеклом'), ('panoramic_glass', 'Панорамное стекло'), ('g_shaped_glass', 'Г-образное стекло'), ('p_shaped_glass', 'П-образное стекло'), ('prismatic_glass', 'Призматическое стекло'), ('two_sided_glass', 'Двухстороннее стекло'), ('without_glass', 'Без стекла')], max_length=32, null=True, verbose_name='Обзор огня'),
        ),
        migrations.AlterField(
            model_name='product',
            name='firebox_material',
            field=models.CharField(blank=True, choices=[('cast_iron', 'Чугунная'), ('steel', 'Стальная'), ('chamotte', 'Шамотная'), ('cellular_cast_iron', 'Цельнолитая чугунная')], max_length=32, null=True, verbose_name='Материал топки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('wood', 'Дровяная'), ('electric', 'Электрическая'), ('gas', 'Газовая'), ('coal', 'Угольная'), ('solid_fuel', 'Твердотопливная'), ('semi_automatic', 'Полуавтоматическая'), ('bioethanol', 'Биоэтанольная'), ('pellet', 'Пеллетная')], max_length=32, null=True, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='product',
            name='heated_volume',
            field=models.CharField(blank=True, choices=[('lt_100', 'до 100 м³'), ('100_150', '100–150 м³'), ('150_200', '150–200 м³'), ('200_250', '200–250 м³'), ('250_300', '250–300 м³'), ('gt_300', 'более 300 м³')], max_length=32, null=True, verbose_name='Площадь/объём отопления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power_kw',
            field=models.CharField(blank=True, choices=[('kw_6', '6 кВт'), ('kw_8', '8 кВт'), ('kw_10', '10 кВт'), ('kw_12', '12 кВт'), ('kw_14', '14 кВт'), ('kw_16', '16 кВт'), ('kw_18', '18 кВт'), ('kw_20', '20 кВт'), ('kw_24', '24 кВт'), ('kw_30', '30 кВт')], max_length=32, null=True, verbose_name='Мощность (кВт)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='steam_volume_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объём парной от, м³'),
        ),
        migrations.AlterField(
            model_name='product',
            name='steam_volume_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объём парной до, м³'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stone_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Масса закладываемых камней, кг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Вес, кг'),
        ),
    ]
