# Generated by Django 5.2.11 on 2026-02-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_remove_product_facing_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='keywords',
            new_name='seo_keywords',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='product_description',
            field=models.TextField(blank=True, verbose_name='Описание страницы товара'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='product_name',
            field=models.CharField(default='1', max_length=255, verbose_name='Название страницы товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='Описание страницы'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название страницы'),
        ),
    ]
