# Generated by Django 5.2.11 on 2026-02-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_rename_keywords_manufacturer_seo_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='product_name',
        ),
    ]
