# Generated by Django 5.2.11 on 2026-02-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_remove_manufacturer_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_discount',
        ),
        migrations.AddField(
            model_name='product',
            name='chimney_connection',
            field=models.CharField(blank=True, choices=[('top', 'Верхнее'), ('rear', 'Заднее'), ('side', 'Боковое')], max_length=16, null=True, verbose_name='Подключение к дымоходу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Обычная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sections',
            field=models.ManyToManyField(to='main_app.section', verbose_name='Разделы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес, кг'),
        ),
        migrations.AlterField(
            model_name='review',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(help_text='Используется в URL', max_length=255, verbose_name='ЧПУ(Slug)'),
        ),
    ]
