# Generated by Django 5.2.11 on 2026-02-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_remove_product_is_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='door_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='firebox_material',
            field=models.CharField(blank=True, choices=[('cast_iron', 'Чугунная'), ('steel', 'Стальная'), ('chamotte', 'Шамотная'), ('cellular_cast_iron', 'Цельнолитая чугунная'), ('vermiculite', 'Вермикулит')], max_length=32, null=True, verbose_name='Материал топки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stone_material',
            field=models.CharField(blank=True, choices=[('natural', 'Натуральный'), ('artificial', 'Искусственный'), ('talc_chlorite', 'Талькохлорит'), ('pyroxenite', 'Пироксенит'), ('amphibolite', 'Амфибалит'), ('marble', 'Мрамор'), ('serpentinite', 'Змеевик'), ('sandstone', 'Песчанник')], max_length=32, null=True, verbose_name='Материал камня'),
        ),
    ]
