# Generated by Django 5.2.11 on 2026-02-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_remove_product_door_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на видео-обзор'),
        ),
    ]
