# Generated by Django 5.2.11 on 2026-02-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_alter_product_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='closed_heater_volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Объём закрытой каменки, л'),
        ),
        migrations.AddField(
            model_name='product',
            name='efficiency',
            field=models.PositiveIntegerField(blank=True, help_text='Указывается в процентах', null=True, verbose_name='КПД, %'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Масса в упаковке, кг'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_preview',
            field=models.ImageField(blank=True, null=True, upload_to='products/video_previews/', verbose_name='Превью видео'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Гарантия, лет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Обычная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='steam_volume_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Объём парной от, м³'),
        ),
        migrations.AlterField(
            model_name='product',
            name='steam_volume_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Объём парной до, м³'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stone_weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Масса закладываемых камней, кг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес, кг'),
        ),
    ]
