# Generated by Django 5.2.11 on 2026-03-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_product_closed_heater_volume_product_efficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sections/images/', verbose_name='Изображение раздела'),
        ),
    ]
