# Generated by Django 5.2.11 on 2026-03-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description_main',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание для главной'),
        ),
    ]
