# Generated by Django 5.2.11 on 2026-03-06 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_section_description_main'),
    ]

    operations = [

        migrations.RunSQL(
            """
            UPDATE main_app_product
            SET power_kw = NULL
            WHERE power_kw !~ '^[0-9]+(\\.[0-9]+)?$';
            """
        ),

        migrations.RunSQL(
            """
            UPDATE main_app_product
            SET power_kw = ROUND(power_kw::numeric)
            WHERE power_kw IS NOT NULL;
            """
        ),

        migrations.RemoveField(
            model_name='product',
            name='cladding_material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='combustion_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='firebox_orientation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_popular',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='product',
            name='steam_room_volume',
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_coal',
            field=models.BooleanField(default=False, verbose_name='Угольная'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_electric',
            field=models.BooleanField(default=False, verbose_name='Электрическая'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_gas',
            field=models.BooleanField(default=False, verbose_name='Газовая'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_pellet',
            field=models.BooleanField(default=False, verbose_name='Пеллетная'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_wood',
            field=models.BooleanField(default=False, verbose_name='Дровяная'),
        ),
        migrations.AddField(
            model_name='product',
            name='lining_material',
            field=models.CharField(blank=True, choices=[('cast_iron', 'Чугунная'), ('steel', 'Стальная'), ('chamotte', 'Шамотная'), ('vermiculite', 'Вермикулит')], max_length=32, null=True, verbose_name='Материал футеровки'),
        ),
        migrations.AddField(
            model_name='product',
            name='long_fire',
            field=models.BooleanField(default=False, verbose_name='Длительное горение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='chimney_diameter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Диаметр дымохода'),
        ),
        migrations.AlterField(
            model_name='product',
            name='closed_heater_volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Объём закрытой каменки (л)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Формат: ДxГxВ в мм', max_length=255, verbose_name='Габариты (Д×Г×В, мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='КПД (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fire_view',
            field=models.CharField(blank=True, choices=[('straight_glass', 'С прямым стеклом'), ('g_shaped_glass', 'Г-образное стекло'), ('p_shaped_glass', 'П-образное стекло'), ('prismatic_glass', 'Призматическое стекло'), ('two_sided_glass', 'Двухстороннее стекло'), ('without_glass', 'Без стекла')], max_length=32, null=True, verbose_name='Обзор огня'),
        ),
        migrations.AlterField(
            model_name='product',
            name='firebox_material',
            field=models.CharField(blank=True, choices=[('cast_iron', 'Чугун'), ('steel', 'Сталь')], max_length=32, null=True, verbose_name='Материал печи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='heated_volume',
            field=models.CharField(blank=True, choices=[('50', '50 м³'), ('75', '75 м³'), ('100', '100 м³'), ('125', '125 м³'), ('150', '150 м³'), ('175', '175 м³'), ('200', '200 м³'), ('225', '225 м³'), ('250', '250 м³'), ('275', '275 м³'), ('300', '300 м³'), ('325', '325 м³'), ('350', '350 м³'), ('375', '375 м³'), ('400', '400 м³')], max_length=32, null=True, verbose_name='Площадь/объём отопления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power_kw',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность (кВт)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на видео-обзор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Гарантия (лет)'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image_first', models.ImageField(upload_to='banners/', verbose_name='Картинка (Первая)')),
                ('image_second', models.ImageField(upload_to='banners/', verbose_name='Картинка (Вторая)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Если выбран — баннер показывается только в бренде', null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.manufacturer', verbose_name='Бренд')),
                ('sections', models.ManyToManyField(blank=True, help_text='Если не выбрано — показывается во всех разделах', to='main_app.section', verbose_name='Разделы')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
