# Generated by Django 5.2.11 on 2026-03-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_remove_product_cladding_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fuel_coal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fuel_electric',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fuel_gas',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fuel_pellet',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fuel_wood',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_in_euro',
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('wood', 'Дровяная'), ('electric', 'Электрическая'), ('gas', 'Газовая'), ('coal', 'Угольная'), ('combine', 'Комбинированная'), ('pellet', 'Пеллетная')], max_length=32, null=True, verbose_name='Тип топлива'),
        ),
    ]
