# Generated by Django 5.2.11 on 2026-03-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_remove_product_fuel_coal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_first',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_second',
        ),
        migrations.AddField(
            model_name='banner',
            name='image_118',
            field=models.ImageField(default='5', upload_to='banners/', verbose_name='Картинка (992x118)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='image_220',
            field=models.ImageField(default='7', upload_to='banners/', verbose_name='Картинка (992X220)'),
            preserve_default=False,
        ),
    ]
