# Generated by Django 5.2.11 on 2026-03-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_remove_banner_image_first_remove_banner_image_second_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_118',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_220',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='9', upload_to='banners/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
