# Generated by Django 5.2.11 on 2026-03-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_remove_banner_image_118_remove_banner_image_220_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='schema',
            field=models.FileField(default='900', upload_to='products/schema/', verbose_name='Схема (формат pdf)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='chimney_connection',
            field=models.CharField(blank=True, choices=[('top', 'Верхнее'), ('rear', 'Заднее'), ('side', 'Боковое'), ('rear_top', 'Заднее и верхнее'), ('top_side', 'Верхнее и боковое')], max_length=16, null=True, verbose_name='Подключение к дымоходу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Формат: Г*Ш*В в мм', max_length=255, verbose_name='Габариты (Г*Ш*В, мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='heated_volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Площадь/объём отопления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Масса в упаковке, кг'),
        ),
    ]
