# Generated by Django 5.2.11 on 2026-03-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_product_schema_alter_product_chimney_connection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='schema',
            field=models.FileField(blank=True, null=True, upload_to='products/schema/', verbose_name='Схема (формат pdf)'),
        ),
    ]
