# Generated by Django 5.2.11 on 2026-03-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_cleanup_product_schema_default_900'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_for_parser',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для парсинга товара'),
        ),
    ]
