# Generated by Django 5.2.11 on 2026-03-15 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_product_url_for_parser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url_for_parser',
        ),
        migrations.CreateModel(
            name='ParserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('status', models.IntegerField(blank=True, choices=[(200, 'Успешно'), (400, 'Некорректный запрос'), (403, 'Доступ запрещён / антибот'), (404, 'Страница не найдена'), (408, 'Таймаут запроса'), (429, 'Слишком много запросов'), (500, 'Ошибка сервера'), (502, 'Плохой шлюз'), (503, 'Сервис недоступен'), (504, 'Таймаут шлюза')], null=True, verbose_name='Статус парсинга')),
                ('error_text', models.TextField(blank=True, null=True, verbose_name='Текст ошибки')),
                ('processing_time', models.DurationField(blank=True, null=True, verbose_name='Время обработки')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parser', to='main_app.product', verbose_name='Товар')),
            ],
        ),
    ]
