# Generated by Django 5.2.11 on 2026-03-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_remove_product_url_for_parser_parserresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parserresult',
            options={'verbose_name': 'Парсинг', 'verbose_name_plural': 'Парсинги'},
        ),
    ]
