# Generated by Django 5.2.11 on 2026-03-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_alter_parserresult_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserresult',
            name='status',
            field=models.IntegerField(blank=True, choices=[(200, 'Успешно'), (301, 'Редирект (возможно ошибка)'), (400, 'Некорректный запрос'), (403, 'Доступ запрещён / антибот'), (404, 'Страница не найдена'), (408, 'Таймаут запроса'), (429, 'Слишком много запросов'), (500, 'Ошибка сервера'), (502, 'Плохой шлюз'), (503, 'Сервис недоступен'), (504, 'Таймаут шлюза')], null=True, verbose_name='Статус парсинга'),
        ),
    ]
