# Generated by Django 5.2.11 on 2026-03-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_alter_parserresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(height_field='Минимум 992/220, а лучше 1984/440. Главное чтобы был формат 9/2.', upload_to='banners/', verbose_name='Картинка'),
        ),
    ]
