# Generated by Django 5.2.11 on 2026-03-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_banner_link_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Минимум 992/220, а лучше 1984/440. Главное чтобы был формат 9/2.', upload_to='banners/', verbose_name='Картинка'),
        ),
    ]
