# Generated by Django 5.2.11 on 2026-03-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_alter_banner_image'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE main_app_parserresult 
                ALTER COLUMN processing_time 
                TYPE timestamp with time zone 
                USING NULL
            """,
            reverse_sql="""
                ALTER TABLE main_app_parserresult 
                ALTER COLUMN processing_time 
                TYPE interval 
                USING NULL
            """,
        ),
        migrations.AlterField(
            model_name='parserresult',
            name='processing_time',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]