# Generated by Django 5.2.11 on 2026-03-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_alter_parserresult_processing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='package_weight',
        ),
        migrations.AddField(
            model_name='product',
            name='oven_weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес печи, кг'),
        ),
        migrations.AlterField(
            model_name='parserresult',
            name='processing_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время обработки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fire_view',
            field=models.CharField(blank=True, choices=[('straight_glass', 'С прямым стеклом'), ('g_shaped_glass', 'Г-образное стекло'), ('p_shaped_glass', 'П-образное стекло'), ('prismatic_glass', 'Призматическое стекло'), ('two_sided_glass', 'Двухстороннее стекло'), ('without_glass', 'Без стекла'), ('semi-circular_glass', 'Полукруглое стекло')], max_length=32, null=True, verbose_name='Обзор огня'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stone_material',
            field=models.CharField(blank=True, choices=[('natural', 'Натуральный'), ('artificial', 'Искусственный'), ('talc_chlorite', 'Талькохлорит'), ('pyroxenite', 'Пироксенит'), ('amphibolite', 'Амфибалит'), ('marble', 'Мрамор'), ('serpentinite', 'Змеевик'), ('sandstone', 'Песчанник'), ('tiles', 'Изарцы')], max_length=32, null=True, verbose_name='Материал камня'),
        ),
    ]
