# Generated by Django 5.2.11 on 2026-04-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_remove_product_package_weight_product_oven_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата монтажа'),
        ),
    ]
