# Generated by Django 5.2.11 on 2026-04-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_review_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturerimage',
            options={'ordering': ['ordering'], 'verbose_name': 'Фото раздела', 'verbose_name_plural': 'Фото разделов'},
        ),
    ]
