# Generated by Django 5.2.11 on 2026-05-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0045_alter_manufacturerimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oven',
            field=models.BooleanField(default=False, verbose_name='Духовка'),
        ),
    ]
