# Generated by Django 5.2.11 on 2026-05-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0046_product_oven'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='product',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('wood', 'Дровяная'), ('electric', 'Электрическая'), ('gas', 'Газовая')], max_length=32, null=True, verbose_name='Тип топлива'),
        ),
    ]
