# Generated by Django 5.2.11 on 2026-06-01 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0047_remove_manufacturer_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='slug (url)')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='Название страницы')),
                ('seo_description', models.TextField(blank=True, verbose_name='Описание страницы')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключевые слова')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='main_app.manufacturer', verbose_name='Производитель')),
                ('products', models.ManyToManyField(blank=True, related_name='collections', to='main_app.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
