# Generated by Django 5.2.11 on 2026-06-25 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0048_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа характеристик',
                'verbose_name_plural': 'Группы характеристик',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название характеристики')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('type', models.CharField(choices=[('choice', 'Выбор из списка'), ('boolean', 'Да/Нет'), ('number', 'Число'), ('text', 'Текст')], max_length=32, verbose_name='Тип характеристики')),
                ('allow_multiple', models.BooleanField(default=False, help_text="Имеет смысл в первую очередь для характеристик типа 'Выбор из списка'", verbose_name='Можно несколько значений')),
                ('unit', models.CharField(blank=True, help_text='Например: кг, кВт, м³, мм', max_length=32, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Вариант характеристики',
                'verbose_name_plural': 'Варианты характеристик',
                'ordering': ['attribute__name', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, verbose_name='Текстовое значение')),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Числовое значение')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='Да/Нет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Значение характеристики товара',
                'verbose_name_plural': 'Значения характеристик товаров',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='chimney_connection',
        ),
        migrations.RemoveField(
            model_name='product',
            name='chimney_diameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='closed_heater_volume',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cooking_panel',
        ),
        migrations.RemoveField(
            model_name='product',
            name='damper',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='door_mechanism',
        ),
        migrations.RemoveField(
            model_name='product',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fire_view',
        ),
        migrations.RemoveField(
            model_name='product',
            name='firebox_material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='firebox_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='glass_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='glass_lift',
        ),
        migrations.RemoveField(
            model_name='product',
            name='heat_exchanger',
        ),
        migrations.RemoveField(
            model_name='product',
            name='heated_volume',
        ),
        migrations.RemoveField(
            model_name='product',
            name='heater_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='installation_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lining_material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long_fire',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oven',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oven_weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='power_kw',
        ),
        migrations.RemoveField(
            model_name='product',
            name='steam_volume_from',
        ),
        migrations.RemoveField(
            model_name='product',
            name='steam_volume_to',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stone_material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stone_weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tank_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty_years',
        ),
        migrations.RemoveField(
            model_name='product',
            name='water_circuit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main_app.product', verbose_name='Товар'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='main_app_pr_slug_ae1452_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='main_app_pr_is_acti_c78481_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['in_stock'], name='main_app_pr_in_stoc_9c187e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='main_app_pr_price_b25f93_idx'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='main_app.attributegroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main_app.productattribute', verbose_name='Характеристика'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='main_app.productattribute', verbose_name='Характеристика'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_values', to='main_app.productattributeoption', verbose_name='Вариант значения'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='main_app.product', verbose_name='Товар'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['slug'], name='main_app_pr_slug_ec04fe_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['type'], name='main_app_pr_type_5f0d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributeoption',
            index=models.Index(fields=['slug'], name='main_app_pr_slug_7c84f6_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributeoption',
            index=models.Index(fields=['is_active'], name='main_app_pr_is_acti_487096_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattributeoption',
            constraint=models.UniqueConstraint(fields=('attribute', 'slug'), name='unique_attribute_option_slug'),
        ),
        migrations.AddConstraint(
            model_name='productattributeoption',
            constraint=models.UniqueConstraint(fields=('attribute', 'value'), name='unique_attribute_option_value'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['product', 'attribute'], name='main_app_pr_product_38db72_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['attribute', 'option'], name='main_app_pr_attribu_f8559e_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['value_number'], name='main_app_pr_value_n_ae37b7_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['value_bool'], name='main_app_pr_value_b_1c6b3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(condition=models.Q(('option__isnull', False)), fields=('product', 'attribute', 'option'), name='unique_product_attribute_option'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(condition=models.Q(('option__isnull', True)), fields=('product', 'attribute'), name='unique_product_attribute_scalar_value'),
        ),
    ]
