# Generated by Django 5.2.11 on 2026-06-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0049_attributegroup_productattribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='group',
        ),
        migrations.DeleteModel(
            name='AttributeGroup',
        ),
    ]
