# Generated by Django 5.2.11 on 2026-06-26 10:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0050_remove_productattribute_group_delete_attributegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_url',
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.PositiveIntegerField(blank=True, help_text='1 — самый высокий приоритет; пустое значение — без приоритета', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Приоритет'),
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='Ссылка на видео')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main_app.product')),
            ],
            options={
                'verbose_name': 'Видео товара',
                'verbose_name_plural': 'Видео товара',
                'ordering': ['ordering', 'id'],
            },
        ),
    ]
