# Generated by Django 5.2.11 on 2026-06-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0051_remove_product_video_url_product_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideo',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Ссылка на видео'),
        ),
    ]
