# Generated by Django 5.2.11 on 2026-06-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0052_alter_productvideo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvideo',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на превью'),
        ),
    ]
