# Generated by Django 5.2.11 on 2026-06-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0053_productvideo_preview_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_preview',
        ),
    ]
