# Generated by Django 5.2.11 on 2026-07-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0054_remove_product_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='hide_in_filter',
            field=models.BooleanField(default=False, verbose_name='Не выводить в фильтр'),
        ),
    ]
