# Generated by Django 5.2.11 on 2026-07-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0055_productattribute_hide_in_filter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ['name'], 'verbose_name': 'Характеристика товара', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='productattributeoption',
            options={'ordering': ['attribute__name', 'value'], 'verbose_name': 'Вариант характеристики', 'verbose_name_plural': 'Значение характеристик'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'Значение характеристики товара', 'verbose_name_plural': 'Выбранные характеристики'},
        ),
    ]
