# Generated by Django 5.2.11 on 2026-07-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0056_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='0 — без ручного приоритета; положительные значения не должны повторяться', verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='0 — без ручного приоритета; положительные значения не должны повторяться внутри характеристики', verbose_name='Приоритет'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['priority'], name='main_app_pr_priorit_50c8d1_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributeoption',
            index=models.Index(fields=['priority'], name='main_app_pr_priorit_673834_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(condition=models.Q(('priority__gt', 0)), fields=('priority',), name='unique_positive_attribute_priority'),
        ),
        migrations.AddConstraint(
            model_name='productattributeoption',
            constraint=models.UniqueConstraint(condition=models.Q(('priority__gt', 0)), fields=('attribute', 'priority'), name='unique_positive_attribute_option_priority'),
        ),
    ]
