# Generated by Django 5.2.11 on 2026-07-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0057_productattribute_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvideo',
            name='preview_url',
        ),
        migrations.AddField(
            model_name='productvideo',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='products/video_previews/', verbose_name='Превью'),
        ),
    ]
