# Generated by Django 5.2.11 on 2026-07-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0058_remove_productvideo_preview_url_productvideo_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='value_number_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Числовое значение от'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_number_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Числовое значение до'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='type',
            field=models.CharField(choices=[('choice', 'Выбор из списка'), ('boolean', 'Да/Нет'), ('number', 'Число'), ('range', 'Диапазон чисел'), ('text', 'Текст')], max_length=32, verbose_name='Тип характеристики'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['value_number_from'], name='main_app_pr_value_n_a0e80b_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['value_number_to'], name='main_app_pr_value_n_77f305_idx'),
        ),
    ]
