# Generated by Django 5.2.11 on 2026-07-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0059_productattributevalue_value_number_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributeoption',
            name='yandex_category_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID рубрики Яндекс'),
        ),
        migrations.AddField(
            model_name='section',
            name='yandex_category_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID рубрики Яндекс'),
        ),
    ]
