# Generated by Django 5.2.11 on 2026-07-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0060_productattributeoption_yandex_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributeoption',
            name='description',
            field=models.TextField(blank=True, verbose_name='Дискрипшен'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='do_not_use_for_direct_url',
            field=models.BooleanField(default=False, verbose_name='Не использовать для прямой ссылки'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='h1',
            field=models.CharField(blank=True, max_length=255, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тайтл'),
        ),
    ]
