# Generated by Django 5.2.11 on 2026-07-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0063_productattribute_do_not_use_for_direct_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='min_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальная цена'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='min_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальная цена'),
        ),
    ]
