# Generated by Django 5.2.11 on 2026-07-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0064_productattribute_min_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
        migrations.RemoveField(
            model_name='section',
            name='menu_name',
        ),
        migrations.AddField(
            model_name='section',
            name='h1',
            field=models.CharField(blank=True, max_length=255, verbose_name='H1 Каталога'),
        ),
    ]
