# Generated by Django 5.2.11 on 2026-07-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0065_remove_section_description_remove_section_menu_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='h1',
            field=models.CharField(blank=True, max_length=255, verbose_name='H1 Каталога'),
        ),
    ]
