# Generated by Django 5.2.11 on 2026-07-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0066_manufacturer_h1'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='priority',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='1 — самый высокий; чем больше число, тем ниже. 0 или пустое значение — без приоритета.', null=True, verbose_name='Приоритет'),
        ),
    ]
